#!/usr/bin/env node
// Renders the desktop UI in Chromium with a mocked Tauri bridge and saves a
// screenshot of every screen: lock, sign-up and onboarding, Home, a DM, a space,
// dialogs and settings. No Tauri build needed.
//   NODE_PATH=$(npm root -g) node apps/desktop/ui-preview.mjs [out-dir]

import { createRequire } from "node:module";
import { mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const require = createRequire(import.meta.url);
const { chromium } = require("playwright");
const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(process.argv[2] ?? join(here, "preview"));
mkdirSync(out, { recursive: true });

// The fake backend lives in ui/demo.js (the app's tour uses it too).
const demoPath = join(here, "ui/demo.js");

const browser = await chromium.launch();
const errors = [];
process.on("exit", () => { if (errors.length) console.error("page errors:\n" + errors.join("\n")); });
async function newPage(startLocked) {
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 }, deviceScaleFactor: 1 });
  page.on("pageerror", (e) => errors.push(String(e)));
  page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
  await page.addInitScript({ path: demoPath });
  await page.addInitScript((locked) => { window.__TAURI__ = anarchyDemo(locked); }, startLocked);
  await page.goto(pathToFileURL(join(here, "ui/index.html")).href);
  await page.evaluate(() => document.fonts.ready);
  return page;
}
let page = await newPage(false);
const shot = async (name) => { await page.waitForTimeout(160); await page.screenshot({ path: join(out, `${name}.png`) }); console.log("saved", name); };
const visible = (sel) => page.waitForSelector(`${sel}:not([hidden])`, { timeout: 5000 }).catch(async (e) => { await page.screenshot({ path: join(out, "FAIL.png") }); throw e; });
// The chats list pops over from the left; open it, pick, and it closes.
async function pick(list, name) {
  // The list lives in the Chats / Channels section only.
  if (await page.isHidden("#drawer-chats")) {
    if (await page.isHidden("#tool-chats")) await page.click('.section >> text=/^(Channels|Chats)$/');
    if (await page.isHidden("#drawer-chats")) await page.click("#tool-chats");
  }
  await page.click(`${list} .side-item >> text="${name}"`);
}
async function openCollections() {
  await page.click('.section >> text=/^Desks$/');
  await page.waitForTimeout(150);
  if (await page.isHidden("#view-desks") && await page.isHidden("#view-desk")) { await page.click('.section >> text=/^Desks$/'); await page.waitForTimeout(150); }
  if (!(await page.isHidden("#view-desks"))) await page.click('#desks-grid .ov-desk >> text="Collections"');
  await page.waitForSelector("#view-desk:not([hidden])", { timeout: 5000 });
}
const folder = (label) => page.click(`.section >> text="${label}"`);

// The first screen: three ways in, none of them needs a server (D38).
await visible("#s-welcome");
await shot("00-first-screen");
await page.click("#go-tour");
await visible("#app");
await visible("#tour-bar");
await page.waitForTimeout(300);
await shot("00b-tour");
await page.click("#tour-end");
await visible("#s-welcome");
await page.click("#go-local");
await page.fill("#local-name", "Maya Chen");
await shot("00c-local-name");
await page.click("#local-back");
await page.click("#go-signin");

// Sign-up and onboarding.
await visible("#s-account");
await visible("#email-form");
await shot("01-welcome");
await page.click("#to-invite");
await page.fill("#invite-link", "https://chat.northwind.org/i/7QK2-MX9F");
await shot("01b-invite");
await page.click("#invite-back");
await page.fill("#email", "maya@northwind.org");
await page.click("#email-send");
await visible("#code-form");
await shot("01c-work-email-finds-company-server");
await page.click("#change-server");
await visible("#s-server");
await page.fill("#server", "anarchy.chat");
await shot("01d-other-server");
await page.click("#server-continue");
await visible("#email-form");
await shot("02-create-account");
await page.fill("#email", "maya.chen@hey.com");
await page.click("#email-send");
await visible("#code-form");
await page.fill("#code", "111111");
await visible("#account-error");
await shot("03-code-wrong");
await page.click("#code-other");
await page.click("#to-anon");
await page.fill("#anon-name", "Night owl");
await shot("04-anonymous");
await page.click("#anon-back");
await page.fill("#email", "maya.chen@hey.com");
await page.click("#email-send");
await visible("#code-form");
await page.fill("#code", "482913");
await visible("#s-usage");
await page.click('.usage[data-usage="freelance"]');
await shot("05-usage");
await page.click("#usage-next");
await visible("#s-lock");
await page.fill("#pass1", "correct horse battery");
await page.fill("#pass2", "correct horse battery");
await shot("06-passphrase");
await page.click("#lock-set");
await visible("#s-card");
await page.fill("#card-name", "Maya Chen");
await page.fill("#card-user", "maya");
await page.click('#avatar-picker [data-avatar="🌊"]');
await page.click('#color-picker [data-color="ocean"]');
await shot("07-welcome-card");
await page.click("#card-save");
await visible("#s-sidekick");
await page.fill("#sk-name", "Pip");
await page.click('#sk-maker .skm-shape[data-shape="case"]');
await page.click('#sk-maker .skm-face[data-face="stern"]');
await page.click("#sk-maker .skm-color");
await shot("07c-sidekick-colour");
await page.click('#sk-maker .skm-swatch[data-c="b07150"]');
await page.click('#sk-maker .skm-state[data-state="thinking"]');
await page.waitForTimeout(500);
await shot("07b-sidekick");
await page.click('#sk-maker .skm-state[data-state="idle"]');
await page.click("#sk-save");
await visible("#app");

// Home and DMs.
await visible("#view-start");
await page.waitForTimeout(250);
await shot("08-home");
await folder("Agenda");
await visible("#view-agenda");
await page.waitForTimeout(200);
await shot("08b-agenda-month");
await page.click('.agenda-mode button[data-mode="week"]');
await shot("08c-agenda-week");
await page.click('.agenda-mode button[data-mode="month"]');
{ const box = await page.locator(".cal-cell.today").boundingBox(); await page.mouse.click(box.x + box.width - 8, box.y + box.height - 6); }
await visible("#quick-event");
await page.fill("#qe-title", "Call with Northwind");
await shot("08d-quick-add");
await page.press("#qe-title", "Enter");
await page.waitForTimeout(200);
await page.click('.agenda-mode button[data-mode="day"]');
await page.waitForTimeout(200);
await shot("08d2-agenda-day");
await page.click('.agenda-mode button[data-mode="month"]');
await page.click("#event-new");
await page.fill("#ev-title", "Call with Northwind");
await shot("08d3-new-event");
await page.click("#event-cancel");
await folder("Notes");
await visible("#view-notes");
await page.waitForTimeout(200);
await shot("08e-notes-page");
await page.click("#note-new");
await page.keyboard.type("Trip to Lisbon");
await page.keyboard.press("Enter");
await page.keyboard.type("/");
await visible("#slash-pop");
await shot("08f-notes-slash");
await page.keyboard.press("ArrowDown");
await page.keyboard.press("Enter");
await page.keyboard.type("Before we go");
await page.keyboard.press("Enter");
await page.keyboard.type("[] ");
await page.keyboard.type("Book the flat");
await page.keyboard.press("Enter");
await page.keyboard.type("Pack the camera");
await page.waitForTimeout(900);
await shot("08g-notes-typed");
await folder("Files");
await visible("#view-drive");
await shot("08i-my-files");
await folder("My tasks");
await visible("#view-board");
await page.waitForTimeout(200);
await shot("08j-my-tasks");
await folder("Notes");
await page.click("#tool-ask");
await page.click("#ask-brief");
await page.waitForTimeout(300);
await shot("08h-todays-brief-docked");
await page.click("#ask-close");
await folder("Home");
await page.fill("#start-dm", "tomas#1881");
await page.press("#start-dm", "Enter");
await visible("#view-convo");
await shot("09-dm");
await page.click("#tool-chats");
await page.click("#tool-chats");
await page.waitForTimeout(200);
await shot("09b-sidebar-popover");
await page.click("#drawer-chats .drawer-pin");
await page.click('.dm-item >> text="Léa Martin"');
await shot("10-dm-empty");
await page.click("#tool-people");
await visible("#drawer-people");
await shot("10b-people-home");
await page.keyboard.press("Escape");
await page.click("#new-dm");
await page.fill("#dm-handle", "nobody#0001");
await page.click("#dm-open");
await visible("#dm-error");
await shot("11-new-message-refused");
await page.click("#dm-cancel");

// Spaces.
await page.click('.rail-btn.space[title="Studio Chen"]');
await visible("#view-space-empty");
await page.waitForTimeout(300);
await shot("12-space-overview");
await page.fill("#search", "acme");
await visible("#search-results");
await page.waitForTimeout(200);
await shot("12b-search");
await page.press("#search", "Escape");
await folder("Files");
await visible("#view-drive");
await page.waitForTimeout(200);
await shot("12c-drive");
await page.click('#drive-rows tr >> text="Clients"');
await page.click('#drive-rows tr >> text="Acme"');
await shot("12d-drive-folder");
await page.click('#drive-crumbs button >> text="Files"');
await page.click('#drive-rows tr >> text="Kickoff notes.md"');
await visible("#preview-edit");
await page.click("#preview-edit");
await visible("#view-notes");
await page.waitForTimeout(200);
await shot("12g-drive-file-in-editor");
await folder("Files");
await page.click('#drive-rows tr >> text="moodboard-direction-2.png"');
await visible("#preview-body img");
await shot("12e-drive-preview");
await page.click("#preview-close");
await page.fill("#drive-search", "pdf");
await shot("12f-drive-search");
await page.fill("#drive-search", "");
await page.click('#drive-rows tr:has-text("moodboard-direction-2.png") button[title="Move to a folder"]');
await visible("#dlg-move");
await page.click('#move-list button >> text="Clients"');
await shot("12h-drive-move");
await page.click("#move-save");
await page.waitForTimeout(200);
await shot("12i-drive-moved");
await page.hover('#drive-rows tr:has-text("rate card")');
await page.click('#drive-rows tr:has-text("rate card") .star');
await page.click('#drive-rows tr:has-text("Kickoff notes.md") button[title="Move to Trash"]');
await page.waitForTimeout(200);
await shot("12j-drive-browser");
await page.click('#drive-pills .pill-tab:has-text("Trash")');
await shot("12k-drive-trash");
await page.click('#drive-rows tr:has-text("Kickoff notes.md") button:has-text("Restore")');
await page.click('#drive-pills .pill-tab:has-text("All")');
await pick("#channel-list", "acme-rebrand");
await visible("#view-convo");
await page.fill("#message", "Deck cover looks great, shipping it to Acme today.");
await page.press("#message", "Enter");
await page.waitForTimeout(300);
await shot("13-channel");
await openCollections();
await visible("#view-desk");
await page.waitForTimeout(250);
await shot("13b-desk");
await page.click('#desk-tabs button >> text="Overdue"');
await page.click("#check-all");
await shot("13c-desk-overdue-selected");
await page.click("#bulk-clear");
await page.click('#desk-tabs button >> text="All"');
await page.click("#new-invoice");
await page.fill("#inv-customer", "Common Goods");
await page.fill("#inv-email", "ap@commongoods.co");
await page.fill("#inv-amount", "1840");
await shot("13d-new-invoice");
await page.click("#invoice-save");
await page.waitForTimeout(250);
await page.click("#notes-brief");
await shot("13e-desk-after-add");
// A client pressed "I've paid" on a payment link.
const claimed = await page.evaluate(() => window.__addClaim());
await openCollections();
await page.waitForTimeout(250);
await shot("13g-desk-client-says-paid");
await page.click(`#desk-rows tr >> text="${claimed}"`);
await visible("#inv-link");
await shot("13h-invoice-payment-link");
await page.click("#invoice-cancel");
await page.click("#desk-paydetails");
await shot("13i-payment-details");
await page.click("#paydetails-cancel");
await page.click('#desk-views button[data-v="clients"]');
await visible("#desk-clients");
await shot("13i2-clients");
await page.click('.client-card >> text="Trendy Terra"');
await visible("#dlg-client");
await shot("13i3-client-card");
await page.click("#client-cancel");
await page.click('.request button >> text="Make a client card"');
await visible("#dlg-client");
await shot("13i6-request-to-client");
await page.click("#client-save");
await page.waitForTimeout(250);
await page.click("#intake-open");
await visible("#dlg-form");
await shot("13i7-intake-form");
await page.click("#form-cancel");
await page.click('#desk-views button[data-v="time"]');
await visible("#desk-time");
await page.fill("#tm-what", "Deck cover, second pass");
await page.selectOption("#tm-client", "c1");
await page.click("#tm-toggle");
await page.waitForTimeout(1300);
await page.check('.time-row:has-text("Lookbook layout") input');
await page.check('.time-row:has-text("Client call") input');
await shot("13i4-time");
await page.click("#time-invoice");
await visible("#dlg-invoice");
await shot("13i5-invoice-from-time");
await page.click("#invoice-cancel");
await page.click('#desk-views button[data-v="invoices"]');
await pick("#channel-list", "acme-rebrand");
await visible("#view-convo");
await page.fill("#message", "");
await page.type("#message", "Is Acme late again? @Col");
await visible("#mention-pop");
await shot("13j-mention-picker");
await page.press("#message", "Enter");
await page.press("#message", "Enter");
await page.waitForTimeout(300);
await shot("13k-desk-mention");
await page.click("#tool-ask");
await page.fill("#ask-input", "acme deck");
await page.press("#ask-input", "Enter");
await page.waitForTimeout(300);
await shot("13l-ask");
await page.click("#ask-server-chat");
await page.waitForTimeout(300);
await shot("13n-sidekick-chat");
await pick("#channel-list", "invoices");
await page.waitForTimeout(300);
page.once("dialog", (d) => d.accept());
await page.click("#convo-sk");
await page.waitForTimeout(400);
await shot("13m-sidekick-on");
page.once("dialog", (d) => d.accept("Clients"));
await page.click("#new-channel-folder");
await page.hover('#channel-list .side-item >> text="acme-rebrand"');
await page.click('#channel-list .side-item:has-text("acme-rebrand") .fold-move');
await page.click('#fold-menu .fold-menu-item >> text="Clients"');
await page.waitForTimeout(200);
await shot("13o-channel-folders");
await page.click('#channel-list .fold-toggle >> text="Clients"');
await page.waitForTimeout(150);
await shot("13p-channel-folder-closed");
await page.click('#channel-list .fold-toggle >> text="Clients"');
await page.click('.section >> text=/^Desks$/');
await page.waitForTimeout(150);
if (await page.isHidden("#view-desks")) await page.click('.section >> text=/^Desks$/');
await visible("#view-desks");
page.once("dialog", (d) => d.accept("Money"));
await page.click("#desks-folder");
await page.waitForTimeout(200);
await page.hover('#desks-grid .ov-desk >> text="Collections"');
await page.click('#desks-grid .ov-desk:has-text("Collections") .fold-move');
await page.click('#fold-menu .fold-menu-item >> text="Money"');
await page.waitForTimeout(400);
await shot("13q-desk-folders");
await page.click('.section >> text=/^Inbox$/');
await visible("#view-inbox");
await shot("13r0-inbox-space");
await page.click("#rail-home");
await page.click('.section >> text=/^Inbox$/');
await visible("#view-inbox");
await page.waitForTimeout(300);
await page.click('.ibx-row:has-text("Invoice 1042")');
await page.waitForTimeout(200);
await shot("13r-inbox");
await page.click('.ibx-row:has-text("Collections")');
await page.waitForTimeout(200);
await shot("13r2-inbox-app-item");
await page.click('.ibx-folder:has-text("Mail")');
await page.keyboard.press("j");
await page.waitForTimeout(200);
await shot("13r3-inbox-mail-folder");
await page.click('.ibx-acct .link');
await page.waitForTimeout(100);
await page.click("#rail-spaces .rail-btn >> nth=0");
await page.waitForTimeout(200);
await page.click("#rail-me");
await shot("13s-presence");
await page.click('#me-presence [data-p="busy"]');
await page.keyboard.press("Escape");
await page.click("body", { position: { x: 700, y: 400 } });
await pick("#channel-list", "acme-rebrand");
await page.click(".thread-sum");
await visible("#thread");
await page.fill("#thread-input", "Perfect, locking it.");
await page.press("#thread-input", "Enter");
await page.waitForTimeout(300);
await shot("13o-thread");
// Threads under stress: other panels take over, the tab reopens it from elsewhere.
await page.click("#tool-people");
await page.waitForTimeout(150);
if (!(await page.isHidden("#thread"))) throw new Error("People should close the thread");
await page.click("#tool-people");
await page.click(".thread-sum");
await page.click("#tool-ask");
if (!(await page.isHidden("#thread"))) throw new Error("Ask should close the thread");
await page.click("#ask-close");
await pick("#channel-list", "invoices");
await page.click(".tab >> text=/^Going with the second/");
await visible("#thread");
await page.waitForTimeout(200);
const where = await page.textContent("#convo-name");
if (!where.includes("acme-rebrand")) throw new Error(`thread tab opened ${where}`);
await page.fill("#thread-input", "Second reply from the tab.");
await page.press("#thread-input", "Enter");
await page.waitForTimeout(300);
const n = await page.textContent(".thread-count");
if (!n.startsWith("5")) throw new Error(`thread count ${n}`);
await shot("13o2-thread-from-tab");
await page.click("#thread-close");
await page.click("#tool-chats");
await page.waitForTimeout(150);
await shot("13p-sidebar-collapsed");
await page.click("#tool-chats");
await page.click("#drawer-chats .drawer-pin");
await page.click("#tool-people");
await page.waitForTimeout(300);
await shot("13q-people-space");
await page.keyboard.press("Escape");
await folder("Desks");
await page.waitForTimeout(150);
await folder("Desks");
await visible("#view-desks");
await page.waitForTimeout(300);
await shot("13r-desks");
await page.click('#desks-grid .ov-desk >> text="Studio handbook"');
await visible("#view-notes");
await page.waitForTimeout(250);
await shot("13r2-shared-pages");
await folder("Desks");
await page.waitForTimeout(150);
if (await page.isHidden("#view-desks")) { await folder("Desks"); await page.waitForTimeout(150); }
await visible("#view-desks");
await page.click('#desks-grid .ov-desk >> text="Launch plan"');
await visible("#view-board");
await page.waitForTimeout(200);
await shot("13s-tasks-board");
await page.dragAndDrop('.bcard[data-id="t2"]', '.bcol[data-col="doing"] .col-cards');
await page.waitForTimeout(250);
const moved = await page.$('.bcol[data-col="doing"] .bcard[data-id="t2"]');
if (!moved) throw new Error("drag and drop didn't move the card");
await page.click('.bcol[data-col="todo"] .col-add-btn');
await page.keyboard.type("Send invoice after sign-off");
await page.keyboard.press("Enter");
await page.waitForTimeout(250);
await page.keyboard.press("Escape");
await shot("13t-tasks-after-drag-and-add");
await page.click('.bcard[data-id="t3"]');
await visible("#dlg-card");
await shot("13u-task-card");
await page.click("#card-cancel");
await folder("Channels");
await page.waitForTimeout(300);
await shot("13v-sidebar-todos");
await page.click('.todo >> nth=0');
await visible("#dlg-card");
await shot("13w-todo-opens-card");
await page.click("#card-cancel");
await page.click("#tool-notifs");
await visible("#drawer-notifs");
await page.waitForTimeout(200);
await shot("13x-notifications");
await page.click('#section-foot .section');
await visible("#view-spaceset");
await shot("13y-space-settings");
await folder("Overview");
await page.click("#rail-me");
await shot("13m-me-popover");
await page.click("#me-settings");
await folder("Files on this computer");
await page.click("#m-enabled");
await page.waitForTimeout(150);
await shot("13n-files-on-this-computer");
await page.click('.rail-btn.space >> nth=0');
await openCollections();
await visible("#view-desk");
await folder("Desks");
await visible("#view-desks");
await page.click("#desks-new");
await shot("13f-new-desk");
await page.click("#desk-cancel");
await page.click("#rail-add");
await page.fill("#space-new-name", "Family");
await page.check('input[name=space-kind][value="personal"]');
await shot("14-create-space");
await page.click("#space-cancel");
await page.click("#tool-people");
await page.click("#space-invite");
await page.click("#sp-create");
await visible("#sp-result");
await shot("15-space-invite");
await page.click("#sp-close");

// Settings.
await page.click("#rail-me"); await page.click("#me-settings");
await visible('.page[data-page="profile"]');
await shot("16-settings-profile");
await page.click("#ps-design");
await page.waitForTimeout(200);
await page.evaluate(() => document.querySelector("#ps-maker").scrollIntoView());
await shot("16b-settings-sidekick-maker");
await page.click("#ps-design");
await folder("Privacy");
await page.check('input[name=dm-policy][value="anyone"]');
await page.check("#humans-only");
await shot("17-settings-privacy");
await folder("Account & device");
await shot("18-settings-account");
await folder("Appearance");
await page.click('#settings-appearance [data-display="dark"]');
await shot("19-appearance-dark");
await page.click("#rail-home");
await pick("#dm-list", "Tomás Ruiz");
await shot("20-dm-dark");
await page.click("#rail-me"); await page.click("#me-settings");
await folder("Appearance");
await page.click('#settings-appearance [data-display="luna"]');
await page.click('.rail-btn.space[title="Studio Chen"]');
await pick("#channel-list", "acme-rebrand");
await shot("21-channel-luna");
await page.close();

// Locked start.
page = await newPage(true);
await visible("#lock");
await shot("22-locked");
await page.fill("#lock-pass", "nope nope nope");
await page.click("#lock-submit");
await visible("#lock-error");
await page.fill("#lock-pass", "correct horse battery");
await page.click("#lock-submit");
await visible("#app");
await shot("23-unlocked-home");
// Starting on this computer, then Home with nothing on a server (D38).
page = await newPage(false);
await visible("#s-welcome");
await page.click("#go-local");
await page.fill("#local-name", "Maya Chen");
await page.click("#local-go");
await visible("#s-usage");
await page.click('.usage[data-usage="freelance"]');
await page.click("#usage-next");
await visible("#s-lock");
await page.click("#lock-skip");
await visible("#s-card");
await page.click("#card-save");
await visible("#s-sidekick");
await page.click("#sk-skip");
await visible("#app");
await page.waitForTimeout(400);
await shot("00d-local-home");
await page.click("#rail-me");
await shot("00e-local-connect");
await page.click("#me-connect");
await visible("#s-account");
await page.waitForTimeout(300);
await shot("00f-connect-from-local");
await page.click("#account-back");
await visible("#app");
await browser.close();
if (errors.length) { console.error("page errors:\n" + errors.join("\n")); process.exit(1); }
