#!/usr/bin/env node
// Compiles design-system/tokens.json into CSS custom properties and copies the
// component stylesheet into each app. Run: node design-system/build.mjs
// CI runs it and fails if the committed output is out of date.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const tokens = JSON.parse(readFileSync(join(here, "tokens.json"), "utf8"));

// Apps ship their own fonts: no stylesheet may pull from Google Fonts or any other CDN.
const OUTPUTS = [join(root, "apps/desktop/ui/ds")];

const themes = tokens.color.themes.map((t) => t.id);
const [first] = themes;
const colorValue = (v, theme) => {
  const raw = typeof v === "string" ? v : (v[theme] ?? v[first]);
  const alias = /^\{(.+)\}$/.exec(raw);
  return alias ? `var(--${alias[1]})` : raw;
};
const decl = (name, value) => `  --${name}: ${value};`;

const blocks = themes.map((theme) => {
  const selector = theme === first ? `:root, [data-theme="${theme}"]` : `[data-theme="${theme}"]`;
  const lines = [
    ...tokens.color.tokens.map((t) => decl(t.name, colorValue(t.value, theme))),
    ...(tokens.shadow?.tokens ?? []).map((t) => decl(t.name, colorValue(t.value, theme))),
  ];
  if (theme === "dark") lines.push("  color-scheme: dark;");
  return `${selector} {\n${lines.join("\n")}\n}`;
});

const scalars = [
  ...tokens.spacing.tokens,
  ...tokens.radius.tokens,
  ...Object.entries(tokens.type.families).map(([k, v]) => ({ name: `font-${k}`, value: v })),
].map((t) => decl(t.name, t.value));

const header = "/* Generated by design-system/build.mjs from tokens.json. Do not edit. */\n";
const tokensCss = `${header}${blocks.join("\n\n")}\n\n:root {\n${scalars.join("\n")}\n}\n`;

const bundleCss = readFileSync(join(here, "components/bundle.css"), "utf8")
  .split("\n")
  .filter((line) => !/^@import url\(["']?https?:/.test(line))
  .join("\n");

for (const dir of [join(here, "dist"), ...OUTPUTS]) {
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "tokens.css"), tokensCss);
  writeFileSync(join(dir, "components.css"), `${header}${bundleCss}`);
}
console.log(`tokens.css: ${themes.length} themes, ${tokens.color.tokens.length} colors`);
